#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

###
# - https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html
#
# @version 1.1.0
###

PROJECT_DIR='.'

JAR_FILE="$PROJECT_DIR/app/build/libs/twandy.jar"

if [[ -s "$PROJECT_DIR/gradlew" ]]; then
  GRADLE="$PROJECT_DIR/gradlew"
else
  GRADLE="gradle"
fi

if [[ ! -s "$JAR_FILE" ]]; then
  # Show commands.
  set -xv

  # We only need the Jar, so try to build it as fast as possible.
  "$GRADLE" jar -x check -x test --parallel

  # Hide commands.
  set +xv
fi

java -jar "$JAR_FILE" "$@"
